### ISSUE TITLE
Review Pertama

### ISSUE THREAD

**Issue by priyandari** [DirgantaraKP/Pendataan-Status-Gizi-Balita#1]
FUTURE

1. Tambahkan sedikit penjelasan bagaimana cara menggunakan program di bagian ini.

2. Berikan kemudahan kepada penggunakan mengenai apakah inputan/pilihan itu isinya Angka atau teks. Contoh pada pertanyaan 

Apakah ada yang perlu di inputkan lagi?
1). Ada
2). Tidak Ada
2

Kalau saya isi Ada dan angka 2 hasilny sama saja kembali ke menu

3. Gizi itu bukanhkan bisa dihitung menggunakan rumus? kemudian nanti jika masuk dalam rentang tertentu kemudian ditentukan statusnya ? ataukah Tabel Median tersebut PATEN tanpa ada rumusnya ?

4. Tambahkan penyimpanan hasil input dan pengecekan gizi balita ke dalam file data_bayi_tanggal.csv (menyimpan nama, berat, dan status gizi), serta updatelah file data_tanggal.csv (menyimpan data tanggal-tanggal pernah dilakukan input dan pengecekan data gizi bayi).

5. Dengan tambahan no4, lakukan penambahan program agar pengguna bisa melihat tanggal-tanggal pernah dilakukan pengecekan, kemudian setelah memilih tanggal maka akan keluar hasil data bayi yang berasal dari file data_bayi_tanggal.csv

6. Keluaran program untuk pengguna ya tidak seperti di bawah ini, tetapi buatlah 'seperti tabel' atau di menurun ke bawah. bukan dalam bentuk list :

Tuliskan nama bayi: Heru
['NAMA', 'JENIS KELAMIN', 'USIA', 'BB', 'INDEKS', 'STATUS']
['Heru', 'Laki-Laki', '45 bulan', '19.0 kg', 1.45, 'Gizi Normal']
----------------

**Comment by priyandari** [comment]
Alur kerja pogram dalam bentuk pdf juga belum ada

**Comment by priyandari** [comment]
Bagian mana dari review tersebut yang sudah dipenuhi harus direspon..agar tidak double check

**Comment by DirgantaraKP** [comment]
-REVIEW YANG SUDAH DI KERJAKAN-
1.) Penjelasan tentang penggunaan program sudah di update dan dapat dilihat dalam (Deskripsi 
     Program kel 9.pdf) dan (Diagram alir kel 9.pdf).
2.) Penjelasan tentang apakah yang harus diinputkan (angka /ketik) pada setiap fitur sudah tertera 
     pada program dan sudah terdapat perbedaan ketika pengguna menginputkan "ada"/"tidak 
     ada"/ menginput selain angka 1 atau 2 (akan menampilkan peringatan serta kembali ke menu 
     awal untuk mengulangi) karena di fitur sebelumnya kami belum menambahkan (else) pada fitur 
     tersebut.
3.) Untuk menghitung gizi kami menggunakan rumus serta tabel yang berasal Kementrian 
     Kesehatan RI, lalu data dari tabel tersebut diolah bersama dengan data balita menggunakan 
     rumus yang sudah paten, penjelasan lebih lanjut bisa dilihat di (Deskripsi program kel 9.pdf) dan 
     referensi program poin ke 7
4.) Kami telah menambahkan fitur penyimpanan data menggunakan fomat .csv (datagizi.csv) 
     dengan memasukan nama balita, jenis kelamin, usia, BB, nilai indeks gizi, status balita, tanggal 
     diperiksa, tanggal lahir bayi, dan dapat dilihat secara langsung didalam program dengan (fitur 3)
5.) Untuk fitur ini (fitur 2) kami menggunakan nama balita (sudah dikonsultasikan sebelumnya 
     bersama bapak via chat WA) untuk mengecek/memanggil data data yang telah diinputkan 
     sebelumnya pada balita tersebut yang bersifat sekali running, jika ingin memeriksa data secara 
     keseluruhan bisa melalui (fitur 3)
6.) Keluaran program untuk pengguna (fitur 2)  sudah diperbaiki menjadi menurun ke bawah.

**Comment by priyandari** [comment]
Bug pada Fitur 2. Tidak bisa cari nama Andi -> lihat kasus issue Duplicate entity

**Comment by DirgantaraKP** [comment]
baik pak kami berusaha memperbaiki dan akan kami jawab di issues selanjutnya terimakasih...

**Comment by priyandari** [comment]
Ok
