### ISSUE TITLE
Duplicate Entity

### ISSUE THREAD

**Issue by priyandari** [DirgantaraKP/Pendataan-Status-Gizi-Balita#6]
Perhatikan data pada Gambar

![Capture2](https://user-images.githubusercontent.com/4914090/84588807-829c7900-ae54-11ea-970c-4bdc414efccc.PNG)

Andi itu adalah bayi yang sama, namun karena ada kesalahan data berat pada input awal, akibatnya data menjadi DUPLIKAT

**Comment by priyandari** [comment]
Karena duplicate entity Fitur 2 progam gak bener

**Comment by priyandari** [comment]
Udah saya coba berkali2 cari nama Andi atau Anggara hasilnya sama.. anak tidak ditemukan

**Comment by AnggaraFirmansyah** [comment]
1.Penjelasan tentang tidak dapat menemukan Andi ataupun Anggara adalah bahwa andi dan anggara adalah data yang sudah tersimpan terlebih dahulu, memang fitur 2 kami awalnnya hanya dapat meng cek data berdasarkan nama namun sumber pencarian data adalah dictionary yang berbeda. Sedangkan andi dan Anggara adalah data yang tersimpan pada CSV. 
Jadi intinya bahwa kesalahan kami adalah pada sumber pengecekan yang tidak menggunakan readcsv untuk dapat meng cek kapanpun kita ingin.
Namun kami sudah memperbaiki agar sumber peng cek an data adalah file csv dan sudah dipisahkan berdasarkan tanggal pendataan.

2. Kemudian untuk mencegah adanya kesalahan dalam input(misal salah pada berat atau tanggal lahir) ,kami menambahkan penanyaan konfirmasi atas kebenaran data, jika peng input sudah yakin untuk menyimpan maka akan tersimpan, jika belum yakin dan dirasa ada kesalahan maka dapat mengulang input dan data belum disimpan.

3.Untuk mengatasi duplicate entity kami menggunakan sudut pandang pen input, bahwa kami menambahkan satu variabel yang mutlak yaitu "NOMOR INDUK ", jadi nomor induk ini dimiliki semua anak dan setiap anak memiliki nomor yang berbeda pastinya. Maka akan sudah dipastikan bahwa nomor berbeda adalah anak yang berbeda

**Comment by priyandari** [comment]
Ok
