### ISSUE TITLE
Bug pada fitur 2

### ISSUE THREAD

**Issue by priyandari** [DirgantaraKP/Pendataan-Status-Gizi-Balita#7]
Coba inputkan lebih dari 1 anak.. lalu coba cari berdasarkan nama.

Behasilkah ?

**Comment by priyandari** [comment]
Perluas kemungkinan bahwa :
1. Ada anak dengan nama sama, cuman salah input berat untuk tanggal pendataan yang sama. Sehingga ini beratnya harus direvisi.

2. Ada anak dengan nama sama, tetapi mereka emang dua bayi yang berbeda karena tanggal lahirnya beda. Nah carinya lebih spesifik . Kemudian si bayi ditimbang pada bulan mei dan juni dan tentunya beratnya beda

**Comment by AnggaraFirmansyah** [comment]
Seperti yang sudah kami usahakan pada comment sebelum nya , untuk penanganan revisi input, kami sudah mengatakan tindakan preventif yaitu memunculkan penanyaan atas kebenaran data(konfirmasi,
Sedangkan untuk memperluas kemungkinan tadi juga jawabanya adalah tentang adanya nomor induk yang merupakan hal spesifik adalah nomor induk yang dimiliki setiap anak

**Comment by priyandari** [comment]
Ok
